// brick_builds.js — FURNITURE BUILT FROM NIMROD BRICKS, AND THE PICTURE OF IT A ROOM DRAWS.
//
// Mike, 2026-10-02: "Can we make things like desks from Nimrod bricks and then have a merged version that is
// actually used in the dashboards? Then you can go into it and edit if you want."
//
// *** WHAT A BRICK BUILD IS. *** An ASSEMBLY: `design-assets/bricks/scenes/<id>.json` (schema
// `nimrod-assembly/1`, generated by the private repo's build123d/nimrod_scenes.py and checked there: every
// brick on the 40 mm grid, no two overlapping, every bracket socket mated). It lists published bricks, each
// with a rotation and a position in mm, its bill of materials, and `plays` -- the room furniture it stands in
// for (a `FURNITURE` key in room_parts.js: 'desk', 'sideTable'). Blender (the private Blender/render_bricks.py)
// bakes each one into ONE decimated GLB (`scenes/<id>_merged.glb`) and pictures of it
// (`renders/<id>_front.png`, `_34.png`, `_34_sm.png`); the assembly's `display` names them.
//
// *** THE SITE DRAWS NO MESH. *** There is no WebGL renderer and no three.js here -- that is Mike's decision,
// still open (it is on his list with both sides). So "the merged version actually used" is, today, its FRONT
// PICTURE: a room draws a brick-built desk as the baked picture of the merged desk, in the desk's own place.
// The picture is GREY and the room TINTS it with the piece's own colour (multiply, masked to the picture's
// shape), so a recipe that recolours its desk still recolours it, and no colour is baked into an asset.
//
// *** THE TABLE BELOW IS THE ROOM'S INDEX OF BUILDS. *** Small and static, so a room draws its first frame
// with the right art instead of a box that swaps when a fetch lands. Its counts are COPIED from the published
// JSON, and dev/brick_builds_test.html fetches that JSON and fails if any of them disagree -- a copied number
// with a check on it, not a copied number that drifts.
//
// *** THE LOOK, PER PIECE: 'bricks' (its picture) or 'drawn' (Design's drawn box), DEFAULT 'bricks' WHERE A
// BUILD EXISTS (Rule 1, argued). ***
//   FOR bricks: it is what Mike asked for -- the brick version "actually used in the dashboards", not kept on a
//   shelf page -- and a Nimrod room furnished with Nimrod bricks is the point of making them.
//   AGAINST: Design drew every room in one illustrated style, and a rendered brick desk is a different kind of
//   picture standing in it (and it loses the drawn desk's drawers); it is also a download (~150 KB for the
//   desk) where the drawn desk costs nothing.
//   So bricks by default, and 'Drawn' is one press away on the piece itself (edit mode, the Look row), saved per
//   piece. If the picture cannot load (offline, a missing file), the piece is drawn -- never an empty box.

export const LOOKS = Object.freeze(['bricks', 'drawn']);
export const LOOK_DEFAULT = 'bricks';
export const LOOK_LABELS = Object.freeze({ bricks: 'Brick-built', drawn: 'Drawn' });

/** The builds, by the room part each plays. `parts` = every brick and bracket (not the connector collars). */
export const BRICK_BUILDS = Object.freeze({
  desk: Object.freeze({ id: 'desk_v1', title: 'Desk', parts: 32, bricks: 24, brackets: 8 }),
  sideTable: Object.freeze({ id: 'side_table_v1', title: 'Side table', parts: 29, bricks: 21, brackets: 8 }),
});

/** Where the published bricks live, relative to this file (so a page under any path finds them). */
export const BRICKS_BASE = new URL('./design-assets/bricks/', import.meta.url).href;
export const BRICKS_PAGE = '/bricks.html';

/** The build a room part plays, or null. */
export const buildFor = (part) => (typeof part === 'string' && Object.hasOwn(BRICK_BUILDS, part) ? BRICK_BUILDS[part] : null);

/** The URLs for a build id (or a brick id): its assembly, its pictures, its merged GLB. */
export function buildUrls(id, base = BRICKS_BASE) {
  const b = String(base).endsWith('/') ? String(base) : `${base}/`;
  return {
    assembly: `${b}scenes/${id}.json`,
    merged: `${b}scenes/${id}_merged.glb`,
    front: `${b}renders/${id}_front.png`,
    threeQuarter: `${b}renders/${id}_34.png`,
    small: `${b}renders/${id}_34_sm.png`,
  };
}

/** The bricks page, filtered to one build's parts. */
export const bricksPageFor = (id) => `${BRICKS_PAGE}?build=${encodeURIComponent(id)}`;

/** A look as data: 'bricks' | 'drawn', anything else null. */
export const normalizeLook = (v) => (LOOKS.includes(v) ? v : null);

/** Per-piece looks as stored ({ objectId: 'bricks' | 'drawn' }): anything else dropped. */
export function normalizeLooks(v) {
  const out = {};
  if (!v || typeof v !== 'object' || Array.isArray(v)) return out;
  for (const [k, x] of Object.entries(v)) if (typeof k === 'string' && k && k.length <= 200 && normalizeLook(x)) out[k] = x;
  return out;
}

/**
 * The look a piece is drawn with: the host's per-piece choice (`looks[id]`), else the recipe's own (`it.look`),
 * else LOOK_DEFAULT -- and always 'drawn' when its part has no build.
 */
export function lookOf(it, looks = null) {
  if (!it || !buildFor(it.part)) return 'drawn';
  return normalizeLook(looks && it.id != null ? looks[it.id] : null) || normalizeLook(it.look) || LOOK_DEFAULT;
}

/**
 * A grey picture, tinted: `color` (any CSS colour, a var() included) MULTIPLIED into the picture inside the
 * picture's own shape. Returns the element (absolutely filling its parent); `onFail(el)` runs if the picture
 * cannot be loaded. `fit`: 'contain' (default) | 'cover'; `position`: CSS position, default 'center bottom'
 * (a piece of furniture stands on its feet). With no colour it is the grey picture as it is.
 */
export function tintedPicture(doc, url, color, { fit = 'contain', position = 'center bottom', onFail = null, cls = '' } = {}) {
  const el = doc.createElement('span');
  if (cls) el.className = cls;
  el.style.cssText = 'position:absolute;inset:0;display:block;isolation:isolate;pointer-events:none';
  if (color) {
    const tint = doc.createElement('span');
    tint.dataset.tint = '';
    tint.style.cssText = 'position:absolute;inset:0;display:block';
    tint.style.background = color;
    const mask = `url("${url}") ${position} / ${fit} no-repeat`;
    tint.style.setProperty('-webkit-mask', mask);
    tint.style.setProperty('mask', mask);
    el.append(tint);
  }
  const img = doc.createElement('img');
  img.alt = '';
  img.decoding = 'async';
  img.draggable = false;
  img.style.cssText = `position:absolute;inset:0;width:100%;height:100%;object-fit:${fit};object-position:${position}`
    + (color ? ';mix-blend-mode:multiply' : '');
  img.addEventListener('error', () => { el.dataset.failed = ''; try { onFail?.(el); } catch (err) { console.error('brick picture', err); } }, { once: true });
  img.src = url;
  el.append(img);
  return el;
}

/** A room piece drawn as its build's front picture (room_parts.js `buildFurniture`'s brick-built twin). */
export function buildBrickArt(doc, part, color, { base = BRICKS_BASE, onFail = null } = {}) {
  const b = buildFor(part);
  if (!b) return null;
  const el = tintedPicture(doc, buildUrls(b.id, base).front, color, { onFail });
  el.classList.add('rm', 'rm-bricks');
  el.dataset.furniture = part;
  el.dataset.build = b.id;
  el.dataset.look = 'bricks';
  return el;
}

/** "Built from 32 Nimrod parts: 24 bricks, 8 brackets" -- for a piece's options. */
export function builtFromWords(b) {
  if (!b) return '';
  const bits = [b.bricks ? `${b.bricks} brick${b.bricks === 1 ? '' : 's'}` : '', b.brackets ? `${b.brackets} bracket${b.brackets === 1 ? '' : 's'}` : ''].filter(Boolean);
  return `Built from ${b.parts} Nimrod part${b.parts === 1 ? '' : 's'}${bits.length ? `: ${bits.join(', ')}` : ''}.`;
}

// *** THE LOOK ROW AND "OPEN ITS BRICKS", FOR ANY HOST THAT OFFERS A PIECE'S OPTIONS IN EDIT MODE. *** The room
// module (modules/room.js `builtTarget`) and a dashboard's own room (arrangement.js `roomTargets`, 2D and 3D) both
// offer them, so the row and the action are declared once, here, beside the builds they describe.
export const LOOK_FIELD = Object.freeze({
  key: 'look', label: 'Look', kind: 'choice', default: LOOK_DEFAULT, level: 'essential',
  help: 'Brick-built: the piece as it is built from Nimrod bricks. Drawn: the drawn picture.',
  options: Object.freeze(LOOKS.map((v) => Object.freeze({ value: v, label: LOOK_LABELS[v] }))),
});
/** A built piece's edit-mode actions: "Built from N parts" and the way into its bricks. [] with no build. */
export const builtActions = (b) => (b ? [{ id: 'bricks', note: builtFromWords(b), label: 'Open its bricks', href: bricksPageFor(b.id) }] : []);
