// packs.js — load and validate a Nimrod content pack (docs/PACK_SCHEMA.md, private repo).
//
// A pack is a JSON file that Trivia, Word Forge, Questions and Lessons all read. The module does
// not care who made it — shipped, hand-written, generated by a local model, or pasted into any
// AI with the prompt at the bottom of the schema doc.
//
// *** THE RULE THAT MAKES PACKS SAFE, ENFORCED HERE RATHER THAN TRUSTED. ***
//
// "A pack is built FROM A SOURCE. It is never recalled from memory. Every pack records where its
// content came from." A model asked to remember trivia invents facts; a model given a source and
// asked to extract from it does not, and a small model does the second job well because reading
// and pulling out facts is much easier than remembering them.
//
// So `source` is not documentation, it is a REQUIRED FIELD, and `validatePack` refuses a pack
// that omits it — the same shape as every other safety rule in this codebase: a promise that is
// only true because something checks it, not because the format says so.
//
// THIS FILE VALIDATES. IT DOES NOT DECIDE WHAT A MODULE DOES WITH A PACK. Trivia, Word Forge and
// Lessons each have their own existing content model, their own settings, their own scoring
// (Trivia's quarter-step ladder already matches the schema's scoring section, because the schema
// was written to describe what the code already does). Wiring each of those to accept a loaded
// pack is deliberately NOT done here — that is a per-module decision about how a pack's items
// merge with or replace what a module already has, and guessing at four different answers to
// that question in one pass is how a codebase ends up with four different guesses. This is the
// one piece every consumer needs regardless of that decision: a pack that fails to validate must
// never reach a module at all.

export const PACK_SCHEMA_VERSION = 'nimrod.pack.v1';
export const PACK_KINDS = ['trivia', 'words', 'lesson'];

// Two folders, so nobody has to remember which is which (PACK_SCHEMA.md): `packs/` is MIT-clean
// and shippable, `packs_local/` is share-alike or unclear licence and stays personal. This file
// does not choose between them — a caller passes the URL — but the names are exported so every
// caller uses the same two strings rather than each inventing its own path.
export const PACK_DIR = 'packs';
export const PACK_DIR_LOCAL = 'packs_local';

/**
 * Every problem found with a pack, as a list of short strings. Empty means sound.
 *
 * *** A LIST, NOT A BOOLEAN. *** A pack that fails to load is exactly the moment somebody most
 * needs to know WHY — did it forget a source, is an item missing its correct answer, is the
 * schema version wrong. A single "invalid" tells a person building a pack nothing they can act
 * on; this is the difference between `check_item` in `make_maths.py` (which names what broke)
 * and a bare pass/fail, applied to hand-authored JSON instead of a generator's own output.
 */
export function validatePack(pack) {
  const bad = [];
  if (!pack || typeof pack !== 'object' || Array.isArray(pack)) {
    return ['not a JSON object'];
  }

  if (pack.schema !== PACK_SCHEMA_VERSION) {
    bad.push(`schema must be "${PACK_SCHEMA_VERSION}", got ${JSON.stringify(pack.schema)}`);
  }
  if (!PACK_KINDS.includes(pack.kind)) {
    bad.push(`kind must be one of ${PACK_KINDS.join(', ')}, got ${JSON.stringify(pack.kind)}`);
  }
  if (!pack.name || typeof pack.name !== 'string') {
    bad.push('name is required');
  }

  // *** THE RULE ITSELF. *** A pack without a source does not load, full stop — this is not a
  // warning, it is the one thing this whole file exists to enforce.
  const src = pack.source;
  if (!src || typeof src !== 'object') {
    bad.push('source is required (a pack built from memory still has to say so, in source.name)');
  } else if (!src.name || typeof src.name !== 'string') {
    bad.push('source.name is required');
  }

  if (!Array.isArray(pack.items) || pack.items.length === 0) {
    bad.push('items must be a non-empty array');
    return bad;   // nothing below can be checked without items
  }

  const itemChecker = { trivia: checkTriviaItem, words: checkWordsItem, lesson: checkLessonItem }[pack.kind];
  if (itemChecker) {
    pack.items.forEach((it, i) => {
      for (const problem of itemChecker(it)) bad.push(`item ${i}: ${problem}`);
    });
  }
  return bad;
}

function checkTriviaItem(it) {
  const bad = [];
  if (!it || typeof it.question !== 'string' || !it.question.trim()) bad.push('question is required');
  if (!Array.isArray(it.answers) || it.answers.length < 3) bad.push('answers needs 3 or more');
  else if (it.answers.some((a) => typeof a !== 'string' || !a.trim())) bad.push('an answer is empty');
  if (typeof it.correct !== 'string' || !it.correct.trim()) bad.push('correct is required');
  // *** THE CORRECT ANSWER MUST ACTUALLY BE ONE OF THE OFFERED ANSWERS. *** A pack that says
  // "correct: Green" over a list that does not contain "Green" is not a typo a player can work
  // around — it is a question with no right answer, silently unwinnable.
  else if (Array.isArray(it.answers) && !it.answers.includes(it.correct)) {
    bad.push('correct must be one of the listed answers');
  }
  if (it.difficulty && !['easy', 'medium', 'hard'].includes(it.difficulty)) {
    bad.push(`difficulty must be easy/medium/hard, got ${JSON.stringify(it.difficulty)}`);
  }
  return bad;
}

function checkWordsItem(it) {
  const bad = [];
  if (!it || typeof it.word !== 'string' || !it.word.trim()) bad.push('word is required');
  if (typeof it.definition !== 'string' || !it.definition.trim()) bad.push('definition is required');
  // decoys is optional in the schema doc's own example count (it shows two), but Word Forge's
  // existing rounds need at least one wrong option to be a multiple-choice question at all.
  if (it.decoys !== undefined) {
    if (!Array.isArray(it.decoys) || it.decoys.length === 0) bad.push('decoys, if present, must be a non-empty array');
    else if (it.decoys.some((d) => typeof d !== 'string' || !d.trim())) bad.push('a decoy is empty');
  }
  // *** ADDED 2026-09-08 — Mike: "Fix the schema." *** Word Forge's own word rows have always
  // carried an example sentence, and the pack schema never did — the gap this file's own header
  // used to leave for "a per-module decision" turned out to be a genuine schema hole, not a
  // wiring choice. NAMED `example`, NOT `sentence` — `PACK_SCHEMA.md`'s own worked example
  // already used `example` (it predates this fix), so that is the published contract; Word
  // Forge's internal field is `sentence` and stays that name internally, the same small rename
  // Trivia's own pack mapping already does (`answer`/`wrong` vs. the pack's `correct`/`answers`).
  // Optional, like `decoys`: a definition without an example is still a usable word, the same
  // way `checkLessonItem` treats a video as genuinely optional below. NOT A BREAKING CHANGE —
  // zero `words`-kind packs exist yet (the one shipped pack is `trivia`), so nothing to migrate.
  if (it.example !== undefined && (typeof it.example !== 'string' || !it.example.trim())) {
    bad.push('example, if present, must be a non-empty string');
  }
  if (it.difficulty && !['easy', 'medium', 'hard'].includes(it.difficulty)) {
    bad.push(`difficulty must be easy/medium/hard, got ${JSON.stringify(it.difficulty)}`);
  }
  return bad;
}

function checkLessonItem(it) {
  const bad = [];
  if (!it || typeof it.topic !== 'string' || !it.topic.trim()) bad.push('topic is required');
  // "A lesson without a video is still a lesson" — video is genuinely optional, so its absence
  // is not checked here at all, only its type when present.
  if (it.video !== undefined && it.video !== null && typeof it.video !== 'string') {
    bad.push('video must be a string url when present');
  }
  if (it.questions !== undefined) {
    if (!Array.isArray(it.questions)) bad.push('questions must be an array when present');
    else it.questions.forEach((q, i) => {
      for (const problem of checkTriviaItem(q)) bad.push(`questions[${i}]: ${problem}`);
    });
  }
  return bad;
}

/**
 * Parse and validate pack TEXT (already fetched). Throws with every problem joined into one
 * message, because a caller that only sees "invalid pack" has to come back here and re-run this
 * function to find out why — the message should already say why.
 */
export function parsePack(text) {
  let json;
  try {
    json = JSON.parse(text);
  } catch (e) {
    throw new Error(`pack is not valid JSON: ${e.message}`);
  }
  const problems = validatePack(json);
  if (problems.length) {
    throw new Error(`pack failed validation:\n  ${problems.join('\n  ')}`);
  }
  return json;
}

/**
 * Fetch a pack by URL and validate it. `fetchImpl` is injectable for tests, the same convention
 * `media_sources.js` and `resolveListing` already use in this codebase.
 */
export async function loadPack(url, { fetchImpl = fetch } = {}) {
  const res = await fetchImpl(url);
  if (!res.ok) throw new Error(`pack "${url}" -> ${res.status}`);
  const text = await res.text();
  try {
    return parsePack(text);
  } catch (e) {
    // The URL, because "pack failed validation" with no filename is useless the moment there is
    // more than one pack on a machine.
    throw new Error(`${url}: ${e.message}`);
  }
}
