// packs.js — load and validate a Nimrod content pack (docs/PACK_SCHEMA.md, private repo).
//
// A pack is a JSON file that Trivia, Word Forge, Questions and Lessons all read. The module does
// not care who made it — shipped, hand-written, generated by a local model, or pasted into any
// AI with the prompt at the bottom of the schema doc.
//
// *** THE RULE THAT MAKES PACKS SAFE, ENFORCED HERE RATHER THAN TRUSTED. ***
//
// "A pack is built FROM A SOURCE. It is never recalled from memory. Every pack records where its
// content came from." A model asked to remember trivia invents facts; a model given a source and
// asked to extract from it does not, and a small model does the second job well because reading
// and pulling out facts is much easier than remembering them.
//
// So `source` is not documentation, it is a REQUIRED FIELD, and `validatePack` refuses a pack
// that omits it — the same shape as every other safety rule in this codebase: a promise that is
// only true because something checks it, not because the format says so.
//
// THIS FILE VALIDATES. IT DOES NOT DECIDE WHAT A MODULE DOES WITH A PACK. Trivia, Word Forge and
// Lessons each have their own existing content model, their own settings, their own scoring
// (Trivia's quarter-step ladder already matches the schema's scoring section, because the schema
// was written to describe what the code already does). Wiring each of those to accept a loaded
// pack is deliberately NOT done here — that is a per-module decision about how a pack's items
// merge with or replace what a module already has, and guessing at four different answers to
// that question in one pass is how a codebase ends up with four different guesses. This is the
// one piece every consumer needs regardless of that decision: a pack that fails to validate must
// never reach a module at all.

export const PACK_SCHEMA_VERSION = 'nimrod.pack.v1';
export const PACK_KINDS = ['trivia', 'words', 'lesson'];

// Two folders, so nobody has to remember which is which (PACK_SCHEMA.md): `packs/` is MIT-clean
// and shippable, `packs_local/` is share-alike or unclear licence and stays personal. This file
// does not choose between them — a caller passes the URL — but the names are exported so every
// caller uses the same two strings rather than each inventing its own path.
export const PACK_DIR = 'packs';
export const PACK_DIR_LOCAL = 'packs_local';

/**
 * Every problem found with a pack, as a list of short strings. Empty means sound.
 *
 * *** A LIST, NOT A BOOLEAN. *** A pack that fails to load is exactly the moment somebody most
 * needs to know WHY — did it forget a source, is an item missing its correct answer, is the
 * schema version wrong. A single "invalid" tells a person building a pack nothing they can act
 * on; this is the difference between `check_item` in `make_maths.py` (which names what broke)
 * and a bare pass/fail, applied to hand-authored JSON instead of a generator's own output.
 */
export function validatePack(pack) {
  const bad = [];
  if (!pack || typeof pack !== 'object' || Array.isArray(pack)) {
    return ['not a JSON object'];
  }

  if (pack.schema !== PACK_SCHEMA_VERSION) {
    bad.push(`schema must be "${PACK_SCHEMA_VERSION}", got ${JSON.stringify(pack.schema)}`);
  }
  if (!PACK_KINDS.includes(pack.kind)) {
    bad.push(`kind must be one of ${PACK_KINDS.join(', ')}, got ${JSON.stringify(pack.kind)}`);
  }
  if (!pack.name || typeof pack.name !== 'string') {
    bad.push('name is required');
  }

  // *** THE RULE ITSELF. *** A pack without a source does not load, full stop — this is not a
  // warning, it is the one thing this whole file exists to enforce.
  const src = pack.source;
  if (!src || typeof src !== 'object') {
    bad.push('source is required (a pack built from memory still has to say so, in source.name)');
  } else if (!src.name || typeof src.name !== 'string') {
    bad.push('source.name is required');
  }

  if (!Array.isArray(pack.items) || pack.items.length === 0) {
    bad.push('items must be a non-empty array');
    return bad;   // nothing below can be checked without items
  }

  const itemChecker = { trivia: checkTriviaItem, words: checkWordsItem, lesson: checkLessonItem }[pack.kind];
  if (itemChecker) {
    pack.items.forEach((it, i) => {
      for (const problem of itemChecker(it)) bad.push(`item ${i}: ${problem}`);
    });
  }
  // PER-ITEM SOURCES (below): a source that is there must be a real one, on any pack; an AI-written or
  // recalled pack must have one on every item.
  for (const problem of itemSourceProblems(pack)) bad.push(problem);
  return bad;
}

function checkTriviaItem(it) {
  const bad = [];
  if (!it || typeof it.question !== 'string' || !it.question.trim()) bad.push('question is required');
  if (!Array.isArray(it.answers) || it.answers.length < 3) bad.push('answers needs 3 or more');
  else if (it.answers.some((a) => typeof a !== 'string' || !a.trim())) bad.push('an answer is empty');
  if (typeof it.correct !== 'string' || !it.correct.trim()) bad.push('correct is required');
  // *** THE CORRECT ANSWER MUST ACTUALLY BE ONE OF THE OFFERED ANSWERS. *** A pack that says
  // "correct: Green" over a list that does not contain "Green" is not a typo a player can work
  // around — it is a question with no right answer, silently unwinnable.
  else if (Array.isArray(it.answers) && !it.answers.includes(it.correct)) {
    bad.push('correct must be one of the listed answers');
  }
  if (it.difficulty && !normalizeDifficulty(it.difficulty)) {
    bad.push(`difficulty must be very easy/easy/medium/hard, got ${JSON.stringify(it.difficulty)}`);
  }
  // `spell` (2026-10-07, ../spell_aloud.js): true on a question whose answers are spellings, so a voice reads
  // each answer letter by letter instead of saying it (saying it gives the right one away). Optional.
  if (it.spell !== undefined && typeof it.spell !== 'boolean') bad.push('spell, if present, must be true or false');
  // `answerKind` (2026-10-07, row 2.63): what the right answer IS, when that is useful to another game: 'person' (a
  // real person: Name that person asks these) or 'character' (somebody made up, in a story, film or myth: asked
  // there too). Optional; tagged by web/tools/tag_answer_kinds.py. Anything else is refused, so a typo is not silently
  // a question no game draws.
  if (it.answerKind !== undefined && !ANSWER_KINDS.includes(it.answerKind)) {
    bad.push(`answerKind, if present, must be one of ${ANSWER_KINDS.join(', ')}`);
  }
  return bad;
}
export const ANSWER_KINDS = Object.freeze(['person', 'character']);

// *** A PACK'S `difficulty` AS A LEVEL (2026-10-05). *** The ladder (rating.js / adaptive_play.js) counts
// levels from 1, the easiest; a question's level is where its rating STARTS, and play moves it from there.
// One level per word, in order, so a question marked hard starts two levels (300 rating points, about 85/15
// odds at rating.js's numbers) above one marked easy. ARGUED against a wider spread (easy 1, medium 3, hard 5):
// the gaps would be a guess about how much harder "medium" is, while the ratings find the real gaps by play
// anyway. Anything else (no difficulty, a word this file does not know) is null: the caller decides what an
// unlevelled item means.
//
// *** "VERY EASY" (Mike, 2026-10-06: "There should be even easier questions for children"). *** A
// fourth word BELOW easy: very easy 1, easy 2, medium 3, hard 4. ARGUED against keeping easy at 1 and putting
// very easy at 0: rating.js has no level below 1 (levelOf, poolLevels and stepFloor all floor at 1, in every
// game), so a level 0 would change the ladder of every game to serve one. Shifting the words up one changes
// what a stored trivia level NUMBER means, so Trivia keeps everybody steady itself (trivia.js TRIVIA_RATING:
// its ratings are read on a scale whose level 2 sits where level 1 used to, so every question's stored rating
// keeps its meaning, and a player's stored floor is moved up one, once). Nothing else reads these numbers.
// Spelled "very easy" in a pack; "very_easy" and "veryeasy" (any case) are read as the same word.
export const DIFFICULTY_LEVELS = Object.freeze({ 'very easy': 1, easy: 2, medium: 3, hard: 4 });
export const DIFFICULTY_WORDS = Object.freeze(Object.keys(DIFFICULTY_LEVELS));
/** A pack's difficulty word, spelled the way packs write it ('very easy' / 'easy' / 'medium' / 'hard'), or null. */
export function normalizeDifficulty(d) {
  const flat = String(d == null ? '' : d).trim().toLowerCase().replace(/[\s_-]+/g, '');
  return DIFFICULTY_WORDS.find((w) => w.replace(/\s+/g, '') === flat) || null;
}
export function difficultyLevel(d) {
  return DIFFICULTY_LEVELS[normalizeDifficulty(d)] || null;
}

function checkWordsItem(it) {
  const bad = [];
  if (!it || typeof it.word !== 'string' || !it.word.trim()) bad.push('word is required');
  if (typeof it.definition !== 'string' || !it.definition.trim()) bad.push('definition is required');
  // decoys is optional in the schema doc's own example count (it shows two), but Word Forge's
  // existing rounds need at least one wrong option to be a multiple-choice question at all.
  if (it.decoys !== undefined) {
    if (!Array.isArray(it.decoys) || it.decoys.length === 0) bad.push('decoys, if present, must be a non-empty array');
    else if (it.decoys.some((d) => typeof d !== 'string' || !d.trim())) bad.push('a decoy is empty');
  }
  // *** ADDED 2026-09-08 — Mike: "Fix the schema." *** Word Forge's own word rows have always
  // carried an example sentence, and the pack schema never did — the gap this file's own header
  // used to leave for "a per-module decision" turned out to be a genuine schema hole, not a
  // wiring choice. NAMED `example`, NOT `sentence` — `PACK_SCHEMA.md`'s own worked example
  // already used `example` (it predates this fix), so that is the published contract; Word
  // Forge's internal field is `sentence` and stays that name internally, the same small rename
  // Trivia's own pack mapping already does (`answer`/`wrong` vs. the pack's `correct`/`answers`).
  // Optional, like `decoys`: a definition without an example is still a usable word, the same
  // way `checkLessonItem` treats a video as genuinely optional below. NOT A BREAKING CHANGE —
  // zero `words`-kind packs exist yet (the one shipped pack is `trivia`), so nothing to migrate.
  if (it.example !== undefined && (typeof it.example !== 'string' || !it.example.trim())) {
    bad.push('example, if present, must be a non-empty string');
  }
  if (it.difficulty && !normalizeDifficulty(it.difficulty)) {
    bad.push(`difficulty must be very easy/easy/medium/hard, got ${JSON.stringify(it.difficulty)}`);
  }
  return bad;
}

function checkLessonItem(it) {
  const bad = [];
  if (!it || typeof it.topic !== 'string' || !it.topic.trim()) bad.push('topic is required');
  // "A lesson without a video is still a lesson" — video is genuinely optional, so its absence
  // is not checked here at all, only its type when present.
  if (it.video !== undefined && it.video !== null && typeof it.video !== 'string') {
    bad.push('video must be a string url when present');
  }
  if (it.questions !== undefined) {
    if (!Array.isArray(it.questions)) bad.push('questions must be an array when present');
    else it.questions.forEach((q, i) => {
      for (const problem of checkTriviaItem(q)) bad.push(`questions[${i}]: ${problem}`);
    });
  }
  return bad;
}

// ---------------------------------------------------------------------------------------------
// PER-ITEM SOURCES (Mike, 2026-10-04: "Shouldn't the sources be noted when the questions are made?")
//
// The pack-level `source` above says where a pack came from. For a pack built FROM one document that
// is enough. For a pack an AI wrote from its own knowledge it is not: "Written by Claude from memory"
// is a true name and it is still nothing a reviewer can check a question against. So each item may
// carry its own `source`, and a pack that says it is AI-written must carry one on EVERY item.
//
// THE SHAPE (argued; docs/PACK_SCHEMA.md, private repo, has the reader's version):
//   "https://..."                                     a link (a string that starts http:// or https://)
//   "Encyclopaedia Britannica, 'Giraffe'"             a named reference, or the line of the pack's own
//                                                     source the item comes from (any other string)
//   { "url": "https://...", "title": "...", "note": "..." }
//   { "ref": "Encyclopaedia Britannica, 'Giraffe'", "note": "..." }
//   { "ref": "common knowledge", "note": "<why no citation is needed>" }
//   [ ...any of those ]                               several sources for one fact
// WHY STRINGS AS WELL AS OBJECTS: the fact-check pass's `checked.sources` was already a list of strings
// (a URL, or "certain"), and lesson questions from transcripts already carry `source` as the quoted line
// (transcript_quiz.js `toLessonQuestion`). One field, read the same way in both. The object form is
// there for a title and a note. WHY "common knowledge" IS ALLOWED, AND ONLY WITH A REASON: "What do we
// call a baby dog?" has no citation worth the name, and demanding one is how a model is pushed into
// inventing a plausible URL; but a bare "common knowledge" is exactly the unexplained "certain" this
// rule exists to replace, so it has to say why. Bare non-answers ("certain", "from memory", ...) are
// refused outright. An empty string or null counts as no source at all.
//
// WHICH PACKS MUST HAVE THEM: `ai_written: true` on the pack or on any item, or `source.kind:
// "recalled"` (written from memory, by anybody). Hand-made packs from a named source do not: their
// pack-level source already names the document, and a person writing questions out of a book should
// not have to cite the book forty times. They MAY carry item sources, and one that is there is checked.
//
// GRANDFATHERING: an AI pack whose `generated` date is before ITEM_SOURCES_FROM (the day the rule was
// made) loads without them, and `itemSourceWarnings` says how many items name nothing — a warning the
// pack loader shows and the review strip shows per question ("Source: none given"). A pack with no
// `generated` date is NOT grandfathered: the date is the only evidence of age it has.
export const ITEM_SOURCES_FROM = '2026-10-04';
export const COMMON_KNOWLEDGE = 'common knowledge';
// Words that answer "where is this from?" with nothing. Lower-case, compared after trimming.
const NOT_A_SOURCE = new Set(['certain', 'sure', 'known', 'well known', 'memory', 'from memory', 'my memory',
  'my own knowledge', 'own knowledge', 'general knowledge', 'unknown', 'none', 'n/a', 'na', '-', 'ai', 'claude']);
const isUrl = (s) => /^https?:\/\/[^\s]+$/i.test(s);
const str = (v) => (typeof v === 'string' ? v.trim() : '');
const isCommon = (ref) => str(ref).toLowerCase() === COMMON_KNOWLEDGE;

/** True when an item's `source` field is absent (missing, null or an empty string). */
const absent = (src) => src === undefined || src === null || (typeof src === 'string' && !src.trim());

/** What is wrong with one item `source` value, or null when it is a real source. */
export function itemSourceProblem(src) {
  if (absent(src)) return 'source is missing';
  if (Array.isArray(src)) {
    if (!src.length) return 'source, as a list, needs at least one entry';
    for (const s of src) { const p = itemSourceProblem(s); if (p) return p; }
    return null;
  }
  if (typeof src === 'string') {
    const s = src.trim();
    if (isCommon(s)) return 'a "common knowledge" source needs a reason: { "ref": "common knowledge", "note": "why" }';
    if (NOT_A_SOURCE.has(s.toLowerCase())) return `source "${s}" names nothing to check against; give a link or a reference work`;
    return null;
  }
  if (typeof src !== 'object') return 'source must be text, an object or a list';
  for (const f of ['url', 'ref', 'title', 'note']) {
    if (src[f] !== undefined && src[f] !== null && typeof src[f] !== 'string') return `source.${f} must be text`;
  }
  const url = str(src.url), ref = str(src.ref);
  if (url && !isUrl(url)) return 'source.url must be a link starting http:// or https://';
  if (!url && !ref) return 'source needs a url or a ref';
  if (!url && isCommon(ref) && !str(src.note)) return 'a "common knowledge" source needs a note saying why';
  if (!url && !isCommon(ref) && NOT_A_SOURCE.has(ref.toLowerCase())) return `source.ref "${ref}" names nothing to check against`;
  return null;
}

/**
 * An item's source(s) as a list of `{ url, ref, title, note }` (only the fields that are there), for
 * showing to a reviewer. [] when there is none or it is not a real source. Never throws.
 */
export function itemSources(src) {
  if (absent(src) || itemSourceProblem(src)) return [];
  const one = (s) => {
    if (typeof s === 'string') return isUrl(s.trim()) ? { url: s.trim() } : { ref: s.trim() };
    const o = {};
    for (const f of ['url', 'ref', 'title', 'note']) if (str(s[f])) o[f] = str(s[f]);
    return o;
  };
  return (Array.isArray(src) ? src : [src]).map(one);
}

/** Does this pack have to name a source on every item? (AI-written, or recalled from memory.) */
export function needsItemSources(pack) {
  if (!pack || typeof pack !== 'object') return false;
  if (pack.ai_written === true) return true;
  if (pack.source && typeof pack.source === 'object' && pack.source.kind === 'recalled') return true;
  return Array.isArray(pack.items) && pack.items.some((it) => it && it.ai_written === true);
}

/** Written before the rule existed, by its own `generated` date. */
export function itemSourcesGrandfathered(pack) {
  const d = pack && typeof pack.generated === 'string' ? pack.generated.trim().slice(0, 10) : '';
  return /^\d{4}-\d{2}-\d{2}$/.test(d) && d < ITEM_SOURCES_FROM;
}

// Every place in a pack a fact lives, with the label validatePack uses for it: trivia and words items,
// and each question inside a lesson item (a lesson item's own `source` counts for all its questions).
function sourcedUnits(pack) {
  const out = [];
  (Array.isArray(pack?.items) ? pack.items : []).forEach((it, i) => {
    if (!it || typeof it !== 'object') return;
    if (pack.kind === 'lesson') {
      if (!absent(it.source)) out.push({ label: `item ${i}`, src: it.source, own: true });
      (Array.isArray(it.questions) ? it.questions : []).forEach((q, j) => {
        if (!q || typeof q !== 'object') return;
        out.push({ label: `item ${i}: questions[${j}]`, src: absent(q.source) ? it.source : q.source, own: !absent(q.source) });
      });
    } else {
      out.push({ label: `item ${i}`, src: it.source, own: true });
    }
  });
  return out;
}

/**
 * The per-item source problems in a pack, as validatePack words them. `strict: true` ignores
 * grandfathering (a test uses it to prove a pack would pass the rule as it stands today).
 */
export function itemSourceProblems(pack, { strict = false } = {}) {
  const bad = [];
  const required = needsItemSources(pack) && (strict || !itemSourcesGrandfathered(pack));
  for (const u of sourcedUnits(pack)) {
    if (absent(u.src)) {
      if (required) bad.push(`${u.label}: source is required (this pack is AI-written or recalled, so every item names where its fact comes from)`);
      continue;
    }
    if (!u.own) continue;            // inherited from its lesson item, which is checked on its own
    const p = itemSourceProblem(u.src);
    if (p) bad.push(`${u.label}: ${p}`);
  }
  return bad;
}

/** A warning (never a refusal) for a grandfathered AI pack whose items name no source. */
export function itemSourceWarnings(pack) {
  if (!needsItemSources(pack) || !itemSourcesGrandfathered(pack)) return [];
  const units = sourcedUnits(pack);
  const missing = units.filter((u) => absent(u.src)).length;
  return missing ? [`${missing} of ${units.length} items name no source of their own (the pack was written before `
    + `${ITEM_SOURCES_FROM}, when that was not yet required), so check those against a source while reviewing`] : [];
}

// ---------------------------------------------------------------------------------------------
// LENGTH TELLS -- a WARNING, never a refusal (row 2.25, Mike 2026-09-28): "Some of the questions you
// could guess the answers because a longer than normal answer always ends up being the correct one."
// A pack whose right answer is the longest option far more often than chance teaches a player to
// measure the options instead of knowing the answer. It is still a valid pack -- the questions are
// not wrong -- so `validatePack` stays the only gate and this only reports, so a pack author sees the
// tell before a player does.
//
// It checks both ends: the right answer being the single LONGEST option, and the single SHORTEST.
// Word Forge's own "better writing" pairs had the opposite tell (the better sentence was the shorter
// one in 3 of 4), and "always the shortest" is as guessable as "always the longest".
//
// "FAR MORE OFTEN THAN CHANCE" IS A NUMBER, SO IT IS ARGUED HERE: with k options and lengths that
// carry no information, the right answer is the unique longest about 1 time in k (ties make it a
// little rarer, so this slightly OVERstates chance and errs toward NOT warning). The per-question
// chances are added up exactly (a Poisson-binomial tail), and the pack is flagged when a count at
// least this high would happen by luck less than `alpha` of the time -- 5% by default, the ordinary
// "unlikely to be luck" line, and an option rather than a constant. Chat's first Harmontown pack had
// the right answer longest in 13 of 24 four-option questions (about 6 expected): flagged. Its rewrite,
// 5 of 24: not flagged.
function tailAtLeast(ps, k) {
  // P(at least k successes) for independent trials with success chances `ps`.
  let dist = [1];
  for (const p of ps) {
    const next = new Array(dist.length + 1).fill(0);
    dist.forEach((v, i) => { next[i] += v * (1 - p); next[i + 1] += v * p; });
    dist = next;
  }
  return dist.slice(k).reduce((a, b) => a + b, 0);
}

// Every question in a pack as {correct, options}: trivia items, lesson items' questions, and words
// items with decoys (a definition among its decoys is the same kind of multiple choice).
function choiceQuestions(pack) {
  const out = [];
  const add = (correct, options) => {
    if (typeof correct !== 'string' || !Array.isArray(options)) return;
    const opts = options.filter((o) => typeof o === 'string');
    if (opts.length >= 2 && opts.includes(correct)) out.push({ correct, options: opts });
  };
  for (const it of (pack && Array.isArray(pack.items) ? pack.items : [])) {
    if (!it) continue;
    if (pack.kind === 'trivia') add(it.correct, it.answers);
    else if (pack.kind === 'lesson') for (const q of it.questions || []) add(q && q.correct, q && q.answers);
    else if (pack.kind === 'words' && Array.isArray(it.decoys)) add(it.definition, [it.definition, ...it.decoys]);
  }
  return out;
}

/**
 * Warnings about a pack that is VALID but guessable by length. A list of plain sentences, empty
 * when there is nothing to say. Never throws.
 */
export function lengthTells(pack, { alpha = 0.05 } = {}) {
  const qs = choiceQuestions(pack);
  if (!qs.length) return [];
  const warnings = [];
  for (const [word, pick] of [['longest', (a, b) => a > b], ['shortest', (a, b) => a < b]]) {
    let hits = 0;
    for (const { correct, options } of qs) {
      const len = correct.trim().length;
      if (options.every((o) => o === correct || pick(len, o.trim().length))) hits += 1;
    }
    const ps = qs.map((q) => 1 / q.options.length);
    const expected = ps.reduce((a, b) => a + b, 0);
    if (hits > expected && tailAtLeast(ps, hits) < alpha) {
      warnings.push(`the right answer is the ${word} option in ${hits} of ${qs.length} questions `
        + `(about ${Math.round(expected)} would be expected by chance), so a player could guess by `
        + `length instead of knowing the answer`);
    }
  }
  return warnings;
}

/**
 * Parse and validate pack TEXT (already fetched). Throws with every problem joined into one
 * message, because a caller that only sees "invalid pack" has to come back here and re-run this
 * function to find out why — the message should already say why.
 */
export function parsePack(text) {
  let json;
  try {
    json = JSON.parse(text);
  } catch (e) {
    throw new Error(`pack is not valid JSON: ${e.message}`);
  }
  const problems = validatePack(json);
  if (problems.length) {
    throw new Error(`pack failed validation:\n  ${problems.join('\n  ')}`);
  }
  return json;
}

/**
 * Fetch a pack by URL and validate it. `fetchImpl` is injectable for tests, the same convention
 * `media_sources.js` and `resolveListing` already use in this codebase.
 */
export async function loadPack(url, { fetchImpl = fetch } = {}) {
  const res = await fetchImpl(url);
  if (!res.ok) throw new Error(`pack "${url}" -> ${res.status}`);
  const text = await res.text();
  try {
    return parsePack(text);
  } catch (e) {
    // The URL, because "pack failed validation" with no filename is useless the moment there is
    // more than one pack on a machine.
    throw new Error(`${url}: ${e.message}`);
  }
}
