// qr.js — a QR encoder, self-contained, no CDN.
//
// *** REWRITTEN 2026-08-28 BECAUSE THE PREVIOUS VERSION DID NOT PRODUCE READABLE CODES. ***
//
// Mike pointed a phone at the pairing QR and nothing happened. Compared module-for-module
// against a reference encoder, every case was wrong — 6% to 36% of modules differed, and the
// version chosen was consistently one size too large. Error correction repairs a dirty lens;
// it cannot repair an encoder.
//
// THE THREE ROOT CAUSES, kept here because each one is a trap worth recognizing again:
//
//   1. `chooseVersion` computed capacity as `dataCodewords - 2 - countBits/8` — a fudge for
//      "mode indicator plus terminator" that is not a whole number of codewords and is not
//      how the arithmetic works. For the pairing URL at level Q it made a symbol that fits
//      version 4 exactly (380 bits into 384) look like it needed version 5. **Header
//      overhead is counted in BITS, alongside the data, and rounded up once at the end.**
//   2. It only ever emitted BYTE mode. `HELLO` and `1234…` are alphanumeric and numeric, and
//      encoding them as bytes wastes 40%+ of the payload — which is why every non-URL case
//      also came out a size too big.
//   3. The error correction, block interleaving and mask selection were wrong, so even at
//      the right version the modules disagreed.
//
// *** AND THE PROCESS LESSON, which is the expensive one: ***
//
// The old test suite checked finder patterns, timing patterns, module counts and format
// bits. ALL OF IT PASSED, on a symbol no phone could read — because **a wrong symbol has
// exactly the same structure as a right one.** Structure is not correctness.
//
// So the test for this file is `dev/qr_oracle_test.html`, which compares EVERY MODULE
// against known-good fixtures generated by `segno` (`dev/gen_qr_fixtures.py`). One differing
// module is a failure. Do not add structural assertions and call it verified.
//
// ---------------------------------------------------------------------------------------
// The implementation follows ISO/IEC 18004. It is ordinary and deliberately unclever: the
// tables are the spec's tables, the steps are the spec's steps, and anything surprising has
// a comment saying which rule it comes from.

export const LEVELS = ['L', 'M', 'Q', 'H'];
export const MAX_VERSION = 40;

// Total codewords (data + error correction) per version.
export const TOTAL_CODEWORDS = [0,
  26, 44, 70, 100, 134, 172, 196, 242, 292, 346,
  404, 466, 532, 581, 655, 733, 815, 901, 991, 1085,
  1156, 1258, 1364, 1474, 1588, 1706, 1828, 1921, 2051, 2185,
  2323, 2465, 2611, 2761, 2876, 3034, 3196, 3362, 3532, 3706,
];

// Error-correction codewords PER BLOCK, indexed [level][version - 1].
const EC_PER_BLOCK = {
  L: [7, 10, 15, 20, 26, 18, 20, 24, 30, 18, 20, 24, 26, 30, 22, 24, 28, 30, 28, 28,
      28, 28, 30, 30, 26, 28, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
  M: [10, 16, 26, 18, 24, 16, 18, 22, 22, 26, 30, 22, 22, 24, 24, 28, 28, 26, 26, 26,
      26, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28],
  Q: [13, 22, 18, 26, 18, 24, 18, 22, 20, 24, 28, 26, 24, 20, 30, 24, 28, 28, 26, 30,
      28, 30, 30, 30, 30, 28, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
  H: [17, 28, 22, 16, 22, 28, 26, 26, 24, 28, 24, 28, 22, 24, 24, 30, 28, 28, 26, 28,
      30, 24, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
};

// How many error-correction BLOCKS, indexed [level][version - 1].
const EC_BLOCKS = {
  L: [1, 1, 1, 1, 1, 2, 2, 2, 2, 4, 4, 4, 4, 4, 6, 6, 6, 6, 7, 8,
      8, 9, 9, 10, 12, 12, 12, 13, 14, 15, 16, 17, 18, 19, 19, 20, 21, 22, 24, 25],
  M: [1, 1, 1, 2, 2, 4, 4, 4, 5, 5, 5, 8, 9, 9, 10, 10, 11, 13, 14, 16,
      17, 17, 18, 20, 21, 23, 25, 26, 28, 29, 31, 33, 35, 37, 38, 40, 43, 45, 47, 49],
  Q: [1, 1, 2, 2, 4, 4, 6, 6, 8, 8, 8, 10, 12, 16, 12, 17, 16, 18, 21, 20,
      23, 23, 25, 27, 29, 34, 34, 35, 38, 40, 43, 45, 48, 51, 53, 56, 59, 62, 65, 68],
  H: [1, 1, 2, 4, 4, 4, 5, 6, 8, 8, 11, 11, 16, 16, 18, 16, 19, 21, 25, 25,
      25, 34, 30, 32, 35, 37, 40, 42, 45, 48, 51, 54, 57, 60, 63, 66, 70, 74, 77, 81],
};

// Alignment-pattern center coordinates, indexed by version. Version 1 has none.
const ALIGN = [null, [],
  [6, 18], [6, 22], [6, 26], [6, 30], [6, 34],
  [6, 22, 38], [6, 24, 42], [6, 26, 46], [6, 28, 50], [6, 30, 54], [6, 32, 58], [6, 34, 62],
  [6, 26, 46, 66], [6, 26, 48, 70], [6, 26, 50, 74], [6, 30, 54, 78], [6, 30, 56, 82],
  [6, 30, 58, 86], [6, 34, 62, 90],
  [6, 28, 50, 72, 94], [6, 26, 50, 74, 98], [6, 30, 54, 78, 102], [6, 28, 54, 80, 106],
  [6, 32, 58, 84, 110], [6, 30, 58, 86, 114], [6, 34, 62, 90, 118],
  [6, 26, 50, 74, 98, 122], [6, 30, 54, 78, 102, 126], [6, 26, 52, 78, 104, 130],
  [6, 30, 56, 82, 108, 134], [6, 34, 60, 86, 112, 138], [6, 30, 58, 86, 114, 142],
  [6, 34, 62, 90, 118, 146],
  [6, 30, 54, 78, 102, 126, 150], [6, 24, 50, 76, 102, 128, 154],
  [6, 28, 54, 80, 106, 132, 158], [6, 32, 58, 84, 110, 136, 162],
  [6, 26, 54, 82, 110, 138, 166], [6, 30, 58, 86, 114, 142, 170],
];

// The two-bit level indicator that goes into the format information. NOT the order of
// `LEVELS` — L is 01 and M is 00, which is the kind of thing that silently produces a symbol
// readers reject as the wrong error level.
const LEVEL_BITS = { L: 0b01, M: 0b00, Q: 0b11, H: 0b10 };

// Alphanumeric mode's 45-character set, in its defined order. Index IS the value.
const ALNUM = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ $%*+-./:';

const MODE = {
  numeric: { indicator: 0b0001, counts: [10, 12, 14] },
  alnum: { indicator: 0b0010, counts: [9, 11, 13] },
  byte: { indicator: 0b0100, counts: [8, 16, 16] },
};

// Character-count indicator width depends on the version BAND, not the version.
function countBitsFor(mode, version) {
  const band = version <= 9 ? 0 : (version <= 26 ? 1 : 2);
  return MODE[mode].counts[band];
}

// ---------------------------------------------------------------------------------------
// mode selection — the cheapest mode the whole string fits in.
//
// Deliberately whole-string rather than segmented. Mixed-mode segmentation packs a little
// tighter, but it multiplies the ways this can be wrong, and the payloads here are short
// URLs and six-character codes. If a case ever needs it, the oracle will show it as a
// version too large rather than as an unreadable symbol.
export function chooseMode(text) {
  if (/^[0-9]*$/.test(text)) return 'numeric';
  for (const ch of text) if (!ALNUM.includes(ch)) return 'byte';
  return 'alnum';
}

const utf8 = (text) => Array.from(new TextEncoder().encode(text));

// How many BITS the payload itself occupies, excluding mode and count indicators.
function payloadBits(text, mode) {
  if (mode === 'numeric') {
    const groups = Math.floor(text.length / 3);
    const rest = text.length % 3;
    return groups * 10 + (rest === 0 ? 0 : rest === 1 ? 4 : 7);
  }
  if (mode === 'alnum') {
    return Math.floor(text.length / 2) * 11 + (text.length % 2) * 6;
  }
  return utf8(text).length * 8;
}

/** Total error-correction codewords at this version and level. */
export function ecCodewords(version, level) {
  return EC_PER_BLOCK[level][version - 1] * EC_BLOCKS[level][version - 1];
}

/** Data codewords available at this version and level. */
export function dataCodewords(version, level) {
  return TOTAL_CODEWORDS[version] - ecCodewords(version, level);
}

/**
 * Every codeword the block layout accounts for — data in every block, plus error correction
 * in every block. It must equal `TOTAL_CODEWORDS[version]` for all 160 combinations.
 *
 * Deliberately computed from `blockLayout` rather than from the tables directly, so it is a
 * real check on the DERIVED split (short blocks, long blocks, the remainder) rather than an
 * arithmetic identity that cannot fail. If a block table is ever mistyped, this is what says
 * so, and it says so for every version at once instead of only the ones a test encodes.
 */
export function tableSum(version, level) {
  const b = blockLayout(version, level);
  return b.shortCount * b.shortLen + b.longCount * b.longLen + b.blocks * b.ecPerBlock;
}

/**
 * How the data codewords divide into blocks.
 *
 * Blocks are not all the same size. The short ones come first, then the long ones, each
 * holding exactly one more codeword — and INTERLEAVING depends on that order, so this
 * returns them in it.
 */
export function blockLayout(version, level) {
  const blocks = EC_BLOCKS[level][version - 1];
  const data = dataCodewords(version, level);
  const shortLen = Math.floor(data / blocks);
  const longCount = data % blocks;
  const shortCount = blocks - longCount;
  return {
    blocks,
    ecPerBlock: EC_PER_BLOCK[level][version - 1],
    shortCount,
    shortLen,
    longCount,
    longLen: shortLen + 1,
    // The spec calls these group 1 and group 2, and so does every other implementation and
    // every reader of this code. Same numbers, the names the standard uses.
    blocksA: shortCount,
    dataA: shortLen,
    blocksB: longCount,
    dataB: shortLen + 1,
  };
}

/**
 * The smallest version that fits this text at this level.
 *
 * *** THE ARITHMETIC THAT WAS WRONG BEFORE. *** Everything is counted in BITS — mode
 * indicator, character count indicator, and payload — and rounded up to codewords ONCE, at
 * the end. The old code subtracted a constant number of codewords as a stand-in for the
 * header, which is both the wrong quantity and the wrong unit, and cost a whole version on a
 * payload that fitted exactly.
 *
 * The count indicator widens at versions 10 and 27, so a version can fail on header width
 * alone; the loop re-measures for every candidate rather than assuming the first one's width.
 */
export function chooseVersionFor(text, level, { min = 1, max = MAX_VERSION, mode = null } = {}) {
  const m = mode || chooseMode(text);
  const bits = payloadBits(text, m);
  for (let v = Math.max(1, min); v <= max; v++) {
    const need = 4 + countBitsFor(m, v) + bits;
    if (need <= dataCodewords(v, level) * 8) return { version: v, mode: m };
  }
  return null;
}

/**
 * Byte-mode version chooser, kept for callers that only know a length.
 * Correct now: header counted in bits, rounded once.
 */
export function chooseVersion(byteLength, level, { min = 1, max = MAX_VERSION } = {}) {
  for (let v = Math.max(1, min); v <= max; v++) {
    const need = 4 + countBitsFor('byte', v) + byteLength * 8;
    if (need <= dataCodewords(v, level) * 8) return v;
  }
  return null;
}

// ---------------------------------------------------------------------------------------
// GF(256) for Reed–Solomon, primitive polynomial 0x11D.
const EXP = new Uint8Array(512);
const LOG = new Uint8Array(256);
(() => {
  let x = 1;
  for (let i = 0; i < 255; i++) {
    EXP[i] = x;
    LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d;
  }
  for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255];
})();

const gfMul = (a, b) => (a === 0 || b === 0 ? 0 : EXP[LOG[a] + LOG[b]]);

// Generator polynomial for `degree` error-correction codewords.
function rsGenerator(degree) {
  let poly = [1];
  for (let d = 0; d < degree; d++) {
    const next = new Array(poly.length + 1).fill(0);
    for (let i = 0; i < poly.length; i++) {
      next[i] ^= poly[i];
      next[i + 1] ^= gfMul(poly[i], EXP[d]);
    }
    poly = next;
  }
  return poly;
}

function rsRemainder(data, degree) {
  const gen = rsGenerator(degree);
  const rem = new Array(degree).fill(0);
  for (const byte of data) {
    const factor = byte ^ rem[0];
    rem.shift();
    rem.push(0);
    for (let i = 0; i < degree; i++) rem[i] ^= gfMul(gen[i + 1], factor);
  }
  return rem;
}

// ---------------------------------------------------------------------------------------
// bitstream -> data codewords, then ECC, then interleave.

function encodeData(text, version, level, mode) {
  const bits = [];
  const push = (value, len) => { for (let i = len - 1; i >= 0; i--) bits.push((value >>> i) & 1); };

  push(MODE[mode].indicator, 4);

  if (mode === 'numeric') {
    push(text.length, countBitsFor('numeric', version));
    let i = 0;
    for (; i + 3 <= text.length; i += 3) push(Number(text.substr(i, 3)), 10);
    const rest = text.length - i;
    if (rest === 1) push(Number(text.substr(i, 1)), 4);
    else if (rest === 2) push(Number(text.substr(i, 2)), 7);
  } else if (mode === 'alnum') {
    push(text.length, countBitsFor('alnum', version));
    let i = 0;
    for (; i + 2 <= text.length; i += 2) {
      push(ALNUM.indexOf(text[i]) * 45 + ALNUM.indexOf(text[i + 1]), 11);
    }
    if (i < text.length) push(ALNUM.indexOf(text[i]), 6);
  } else {
    const bytes = utf8(text);
    push(bytes.length, countBitsFor('byte', version));
    for (const b of bytes) push(b, 8);
  }

  const capacity = dataCodewords(version, level) * 8;
  if (bits.length > capacity) throw new Error('qr: data does not fit the chosen version');

  // Terminator: up to four zero bits, and NOT more than the space left.
  for (let i = 0; i < 4 && bits.length < capacity; i++) bits.push(0);
  // Pad to a codeword boundary.
  while (bits.length % 8) bits.push(0);

  const words = [];
  for (let i = 0; i < bits.length; i += 8) {
    let v = 0;
    for (let j = 0; j < 8; j++) v = (v << 1) | bits[i + j];
    words.push(v);
  }
  // Then the two alternating pad codewords, forever, until the block is full.
  const pads = [0xec, 0x11];
  for (let i = 0; words.length < dataCodewords(version, level); i++) words.push(pads[i % 2]);
  return words;
}

function interleave(words, version, level) {
  const { blocks, ecPerBlock, shortCount, shortLen } = blockLayout(version, level);

  const dataBlocks = [];
  const ecBlocks = [];
  let at = 0;
  for (let b = 0; b < blocks; b++) {
    const len = b < shortCount ? shortLen : shortLen + 1;
    const block = words.slice(at, at + len);
    at += len;
    dataBlocks.push(block);
    ecBlocks.push(rsRemainder(block, ecPerBlock));
  }

  // Data codewords first, taking column `i` from every block that has one — the short blocks
  // simply run out first, which is why their contents had to come first above.
  const out = [];
  const maxData = Math.max(...dataBlocks.map((b) => b.length));
  for (let i = 0; i < maxData; i++) {
    for (const b of dataBlocks) if (i < b.length) out.push(b[i]);
  }
  // Then all the error-correction codewords, the same way. These are all the same length.
  for (let i = 0; i < ecPerBlock; i++) {
    for (const b of ecBlocks) out.push(b[i]);
  }
  return out;
}

// ---------------------------------------------------------------------------------------
// the matrix

const SIZE_OF = (version) => 17 + version * 4;

function blank(size) {
  return Array.from({ length: size }, () => new Array(size).fill(null));
}

function placeFinder(m, r, c) {
  for (let i = -1; i <= 7; i++) {
    for (let j = -1; j <= 7; j++) {
      const y = r + i, x = c + j;
      if (y < 0 || x < 0 || y >= m.length || x >= m.length) continue;
      const inner = i >= 0 && i <= 6 && j >= 0 && j <= 6
        && (i === 0 || i === 6 || j === 0 || j === 6 || (i >= 2 && i <= 4 && j >= 2 && j <= 4));
      m[y][x] = inner ? 1 : 0;
    }
  }
}

/** Everything that is function pattern rather than data, as a boolean map. */
function reservedMap(version, size) {
  const res = Array.from({ length: size }, () => new Array(size).fill(false));
  const mark = (r, c) => { if (r >= 0 && c >= 0 && r < size && c < size) res[r][c] = true; };

  // finders + separators
  for (const [r, c] of [[0, 0], [0, size - 7], [size - 7, 0]]) {
    for (let i = -1; i <= 7; i++) for (let j = -1; j <= 7; j++) mark(r + i, c + j);
  }
  // timing
  for (let i = 0; i < size; i++) { mark(6, i); mark(i, 6); }
  // alignment
  const centers = ALIGN[version] || [];
  for (const a of centers) {
    for (const b of centers) {
      // Not where the finders are.
      if ((a === 6 && b === 6) || (a === 6 && b === size - 7) || (a === size - 7 && b === 6)) continue;
      for (let i = -2; i <= 2; i++) for (let j = -2; j <= 2; j++) mark(a + i, b + j);
    }
  }
  // format information (both copies) + the always-dark module
  for (let i = 0; i < 9; i++) { mark(8, i); mark(i, 8); }
  for (let i = 0; i < 8; i++) { mark(8, size - 1 - i); mark(size - 1 - i, 8); }
  mark(size - 8, 8);
  // version information, versions 7 and up
  if (version >= 7) {
    for (let i = 0; i < 6; i++) {
      for (let j = 0; j < 3; j++) { mark(i, size - 11 + j); mark(size - 11 + j, i); }
    }
  }
  return res;
}

export function reservedModules(version) { return reservedMap(version, SIZE_OF(version)); }

function placePatterns(m, version) {
  const size = m.length;
  placeFinder(m, 0, 0);
  placeFinder(m, 0, size - 7);
  placeFinder(m, size - 7, 0);

  for (let i = 8; i < size - 8; i++) {
    const v = i % 2 === 0 ? 1 : 0;
    m[6][i] = v;
    m[i][6] = v;
  }

  const centers = ALIGN[version] || [];
  for (const a of centers) {
    for (const b of centers) {
      if ((a === 6 && b === 6) || (a === 6 && b === size - 7) || (a === size - 7 && b === 6)) continue;
      for (let i = -2; i <= 2; i++) {
        for (let j = -2; j <= 2; j++) {
          m[a + i][b + j] = (Math.abs(i) === 2 || Math.abs(j) === 2 || (i === 0 && j === 0)) ? 1 : 0;
        }
      }
    }
  }

  m[size - 8][8] = 1;              // the module that is always dark
}

// BCH(15,5) format information, XOR-masked with 0x5412 so an all-zero format is not all-zero.
export function formatBits(level, mask) {
  const data = (LEVEL_BITS[level] << 3) | mask;
  let rem = data << 10;
  for (let i = 14; i >= 10; i--) if ((rem >>> i) & 1) rem ^= 0x537 << (i - 10);
  return ((data << 10) | rem) ^ 0x5412;
}

// BCH(18,6) version information, versions 7 and up.
export function versionBits(version) {
  let rem = version << 12;
  for (let i = 17; i >= 12; i--) if ((rem >>> i) & 1) rem ^= 0x1f25 << (i - 12);
  return (version << 12) | rem;
}

function placeFormat(m, level, mask) {
  const size = m.length;
  const bits = formatBits(level, mask);

  // *** INDEX 0 IS THE MOST SIGNIFICANT BIT. ***
  //
  // This is the bug that survived the rewrite for one round, and it is worth naming because
  // it is invisible: the format VALUE was already correct and matched the spec's table
  // exactly, but both copies were written out least-significant-bit first. The result is the
  // 15-bit string reversed — a symbol whose data area is perfect and whose format block is
  // gibberish, so a reader rejects it before it ever looks at the payload.
  //
  // It also poisoned mask selection, because the penalty score is computed over the whole
  // matrix including these modules: a wrong format block scores differently, so a different
  // mask wins. One reversed loop, two unrelated-looking symptoms.
  const bit = (i) => (bits >>> (14 - i)) & 1;

  // Copy one, around the top-left finder: MSB at (8,0), rightwards along row 8, then up
  // column 8. Column 6 is skipped — it is the timing pattern.
  for (let i = 0; i <= 5; i++) m[8][i] = bit(i);
  m[8][7] = bit(6);
  m[8][8] = bit(7);
  m[7][8] = bit(8);
  for (let i = 9; i <= 14; i++) m[14 - i][8] = bit(i);

  // Copy two: MSB at the BOTTOM of column 8, working up; then the remaining eight bits along
  // row 8 at the right-hand edge.
  for (let i = 0; i <= 6; i++) m[size - 1 - i][8] = bit(i);
  for (let i = 7; i <= 14; i++) m[8][size - 15 + i] = bit(i);
}

function placeVersion(m, version) {
  if (version < 7) return;
  const size = m.length;
  const bits = versionBits(version);
  for (let i = 0; i < 18; i++) {
    const b = (bits >>> i) & 1;
    const r = Math.floor(i / 3);
    const c = i % 3;
    m[r][size - 11 + c] = b;
    m[size - 11 + c][r] = b;
  }
}

// Zig-zag placement: two-module-wide columns, right to left, alternating direction, and
// SKIPPING the vertical timing column entirely rather than stepping over it.
function placeData(m, reserved, codewords) {
  const size = m.length;
  let bitIndex = 0;
  const nextBit = () => {
    const byte = codewords[bitIndex >> 3];
    const bit = byte === undefined ? 0 : (byte >>> (7 - (bitIndex & 7))) & 1;
    bitIndex++;
    return bit;
  };

  let upward = true;
  for (let right = size - 1; right >= 1; right -= 2) {
    if (right === 6) right = 5;                 // the timing column is not part of any pair
    for (let step = 0; step < size; step++) {
      const row = upward ? size - 1 - step : step;
      for (const col of [right, right - 1]) {
        if (reserved[row][col]) continue;
        m[row][col] = nextBit();
      }
    }
    upward = !upward;
  }
}

const MASKS = [
  (i, j) => (i + j) % 2 === 0,
  (i) => i % 2 === 0,
  (i, j) => j % 3 === 0,
  (i, j) => (i + j) % 3 === 0,
  (i, j) => (Math.floor(i / 2) + Math.floor(j / 3)) % 2 === 0,
  (i, j) => ((i * j) % 2) + ((i * j) % 3) === 0,
  (i, j) => ((((i * j) % 2) + ((i * j) % 3)) % 2) === 0,
  (i, j) => ((((i + j) % 2) + ((i * j) % 3)) % 2) === 0,
];

export function maskFunction(index) { return MASKS[index]; }

// The four penalty rules. These decide WHICH mask is used, so getting one subtly wrong
// produces a perfectly readable symbol that simply is not the same one anybody else makes —
// which is exactly what the oracle catches.
export function penaltyScore(m) { return penalty(m); }

function penalty(m) {
  const n = m.length;
  let score = 0;

  // Rule 1: runs of five or more of the same color, in every row and every column.
  const runs = (get) => {
    for (let a = 0; a < n; a++) {
      let run = 1;
      for (let b = 1; b < n; b++) {
        if (get(a, b) === get(a, b - 1)) run++;
        else { if (run >= 5) score += run - 2; run = 1; }
      }
      if (run >= 5) score += run - 2;
    }
  };
  runs((a, b) => m[a][b]);
  runs((a, b) => m[b][a]);

  // Rule 2: every 2x2 block of one color.
  for (let r = 0; r < n - 1; r++) {
    for (let c = 0; c < n - 1; c++) {
      const v = m[r][c];
      if (v === m[r][c + 1] && v === m[r + 1][c] && v === m[r + 1][c + 1]) score += 3;
    }
  }

  // Rule 3: the finder-like pattern 1011101 with four light modules on either side.
  const A = [1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0];
  const B = [0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1];
  const hit = (get, a, b) => {
    for (let k = 0; k < 11; k++) if (get(a, b + k) !== A[k]) return false;
    return true;
  };
  const hitB = (get, a, b) => {
    for (let k = 0; k < 11; k++) if (get(a, b + k) !== B[k]) return false;
    return true;
  };
  for (const get of [(a, b) => m[a][b], (a, b) => m[b][a]]) {
    for (let a = 0; a < n; a++) {
      for (let b = 0; b + 11 <= n; b++) {
        if (hit(get, a, b) || hitB(get, a, b)) score += 40;
      }
    }
  }

  // Rule 4: how far the dark proportion strays from half.
  let dark = 0;
  for (let r = 0; r < n; r++) for (let c = 0; c < n; c++) if (m[r][c]) dark++;
  const pct = (dark * 100) / (n * n);
  score += 10 * Math.floor(Math.abs(pct - 50) / 5);

  return score;
}

/**
 * Encode `text` and return the finished matrix.
 *
 * `{ version, level, size, mask, modules }` — `modules[row][col]` is 1 for dark.
 */
export function qrMatrix(text, {
  level = 'M', minVersion = 1, maxVersion = MAX_VERSION, mask = null,
} = {}) {
  const s = String(text == null ? '' : text);
  if (!LEVELS.includes(level)) throw new Error(`qr: unknown level "${level}"`);

  const chosen = chooseVersionFor(s, level, { min: minVersion, max: maxVersion });
  if (!chosen) throw new Error('qr: text does not fit any version at this level');
  const { version, mode } = chosen;
  const size = SIZE_OF(version);

  const codewords = interleave(encodeData(s, version, level, mode), version, level);
  const reserved = reservedMap(version, size);

  const build = (maskIndex) => {
    const m = blank(size);
    placePatterns(m, version);
    placeVersion(m, version);
    placeFormat(m, level, maskIndex);
    placeData(m, reserved, codewords);
    const fn = MASKS[maskIndex];
    for (let r = 0; r < size; r++) {
      for (let c = 0; c < size; c++) {
        if (!reserved[r][c] && fn(r, c)) m[r][c] ^= 1;
      }
    }
    // Remainder bits, and anything the data did not reach, are light.
    for (let r = 0; r < size; r++) for (let c = 0; c < size; c++) if (m[r][c] == null) m[r][c] = 0;
    return m;
  };

  if (mask != null) {
    return { version, level, size, mask, modules: build(mask) };
  }

  let best = null, bestScore = Infinity, bestMask = 0;
  for (let i = 0; i < 8; i++) {
    const m = build(i);
    const p = penalty(m);
    if (p < bestScore) { bestScore = p; best = m; bestMask = i; }
  }
  return { version, level, size, mask: bestMask, modules: best };
}

/** The same matrix as a standalone SVG string. */
export function qrSVG(text, {
  level = 'M', quiet = 4, dark = '#000000', light = '#ffffff',
  title = '', ...rest
} = {}) {
  const { modules, size } = qrMatrix(text, { level, ...rest });
  const total = size + quiet * 2;
  let d = '';
  for (let r = 0; r < size; r++) {
    for (let c = 0; c < size; c++) {
      if (modules[r][c]) d += `M${c + quiet} ${r + quiet}h1v1h-1z`;
    }
  }
  const label = title
    ? `<title>${String(title).replace(/[<>&"]/g, (ch) => `&#${ch.charCodeAt(0)};`)}</title>`
    : '';
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${total} ${total}" `
    + `shape-rendering="crispEdges" role="img"${title ? '' : ' aria-hidden="true"'}>`
    + `${label}<rect width="${total}" height="${total}" fill="${light}"/>`
    + `<path d="${d}" fill="${dark}"/></svg>`;
}
