#!/usr/bin/env python3
"""build_aac_sets.py - COPY CLAUDE DESIGN'S AAC SYMBOL SETS IN, AND WRITE THEIR MANIFEST.

Claude Design delivered the board's 55 words in ten styles on 2026-09-28. One of the ten (the
unthemed root folder) is byte-for-byte what `web/client/aac_symbols.js` already draws, so it is
NOT copied - the board's own drawings are that set. The other nine are copied into
`web/client/design-assets/aac/<set>/<word>.svg`, and `web/client/aac_sets_data.js` is written
from them: which words each set drew, and every colour each word's drawing uses. The board
needs the colours to measure a drawing against the card it is about to sit on (`aac_sets.js`).

EVERY FILE IS CHECKED ON THE WAY IN, AND A FAILURE STOPS THE COPY:
  * no <script>, no on* handler, no javascript:, no <foreignObject>, no <image>;
  * no href / xlink:href / url(...) pointing anywhere but inside the file;
  * no <text> at all - Design once drew the name of the person this project was first built for
    into its sample signs, and the public site must never carry it.
The C2PA content credential in each file's <metadata> is kept, as it was for the signs.

USAGE (from the repo root):
    py -3.13 web/tools/build_aac_sets.py <path to the delivered icons folder>

`dev/aac_sets_test.html` re-reads every copied file and fails if this manifest stops matching it.
"""
import json
import os
import re
import shutil
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
OUT_DIR = os.path.join(REPO, 'web', 'client', 'design-assets', 'aac')
DATA_JS = os.path.join(REPO, 'web', 'client', 'aac_sets_data.js')

# Design's folder name -> the id the board uses. The same today; the map is where a rename lands.
SETS = ['color', 'mono', 'fall', 'steampunk', 'cyberpunk', 'cozy', 'winter', 'ocean', 'night']

UNSAFE = [
    (re.compile(r'<script', re.I), 'a <script> element'),
    (re.compile(r'\son[a-z]+\s*=', re.I), 'an on* event handler'),
    (re.compile(r'javascript:', re.I), 'a javascript: URL'),
    (re.compile(r'<foreignObject', re.I), 'a <foreignObject>'),
    (re.compile(r'<image\b', re.I), 'an <image> (external picture)'),
    (re.compile(r'(?:xlink:)?href\s*=\s*["\'](?!#)', re.I), 'an href that leaves the file'),
    (re.compile(r'url\(\s*["\']?(?!#)', re.I), 'a url() that leaves the file'),
    (re.compile(r'<text\b', re.I), 'drawn text (a sample word could name a person)'),
]
COLOUR = re.compile(r'(?:stroke|fill)\s*=\s*"(#[0-9a-fA-F]{3,8}|currentColor)"')


def drawing(svg):
    return re.sub(r'<metadata>.*?</metadata>', '', svg, flags=re.S)


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 2
    src = argv[1]
    manifest = {}
    problems = []
    for set_id in SETS:
        folder = os.path.join(src, set_id)
        words = {}
        for name in sorted(os.listdir(folder)):
            if not name.endswith('.svg'):
                continue
            raw = open(os.path.join(folder, name), encoding='utf-8').read()
            body = drawing(raw)
            for pat, what in UNSAFE:
                if pat.search(body):
                    problems.append(f'{set_id}/{name}: {what}')
            cols = []
            for m in COLOUR.finditer(body):
                c = m.group(1)
                c = 'currentColor' if c.lower() == 'currentcolor' else c.lower()
                if c not in cols:
                    cols.append(c)
            words[name[:-4]] = cols
        manifest[set_id] = words
    if problems:
        print('REFUSED - nothing copied:')
        for p in problems:
            print('  ' + p)
        return 1

    for set_id in SETS:
        dest = os.path.join(OUT_DIR, set_id)
        os.makedirs(dest, exist_ok=True)
        for word in manifest[set_id]:
            shutil.copyfile(os.path.join(src, set_id, word + '.svg'), os.path.join(dest, word + '.svg'))

    lines = [
        '// aac_sets_data.js - GENERATED by web/tools/build_aac_sets.py. Do not edit by hand; re-run it.',
        '//',
        "// For each of Claude Design's AAC symbol sets: every word it drew, and every colour that word's",
        '// drawing uses (lower-case hex, in the order they first appear). `dev/aac_sets_test.html`',
        '// re-reads the files and fails if this stops matching them.',
        '',
        'export const SET_WORDS = {',
    ]
    for set_id in SETS:
        lines.append(f'  {set_id}: {{')
        for word, cols in manifest[set_id].items():
            lines.append(f'    {json.dumps(word)}: {json.dumps(cols)},')
        lines.append('  },')
    lines.append('};')
    lines.append('')
    with open(DATA_JS, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    total = sum(len(w) for w in manifest.values())
    print(f'copied {total} files in {len(SETS)} sets to {OUT_DIR}; wrote {DATA_JS}')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
